name:                instance6
version:             0.1.0.0
github:              "https://github.com/onurridvanoglu/Haskell-Book-Solutions"
license:             BSD3
author:              "Onur Rıdvanoğlu"
maintainer:          "onurridvanoglu@gmail.com"
copyright:           "2019 Onur Rıdvanoğlu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/instance6#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  instance6-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - instance6

tests:
  instance6-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - instance6
